In [1]:
import numpy as np
import pandas as pd
from konlpy.tag import Kkma
from sklearn.model_selection import train_test_split    # X스플릿
from sklearn.tree import DecisionTreeClassifier         # 디시전트리
from sklearn.model_selection import cross_val_score     # 교차검증
from sklearn.neighbors import KNeighborsClassifier      # KNN
from sklearn.ensemble import RandomForestClassifier     # 랜덤포레스트
from sklearn.model_selection import GridSearchCV        # 그리드서치
from sklearn.preprocessing import StandardScaler        # 스탠다드스케일러
from sklearn.preprocessing import RobustScaler          # 로버스트 스케일러
from sklearn.preprocessing import MinMaxScaler          # 민맥스 스케일러
from sklearn.preprocessing import Normalizer            # 노멀라이저 스케일러
from sklearn.ensemble import VotingClassifier           # 보팅
from sklearn.ensemble import AdaBoostClassifier         # 에이다부스팅
from sklearn.ensemble import GradientBoostingClassifier # 그래디언트부스팅
from sklearn.model_selection import RandomizedSearchCV  # 랜덤서치
from xgboost import XGBClassifier                       # XGBoost
from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score

In [169]:
# !pip install xgboost

In [5]:
data = pd.read_csv('최종학습데이터.csv', encoding='cp949')

In [6]:
data

웹툰 제목      회차 제목  회차    조회수  회차별 별점  별점 참여인원수  좋아요수  댓글수  정식연재  \
0      팬시x팬시         1화   1  69288    9.47       559   693  138     1   
1      팬시x팬시         2화   2  47876    9.48       418   561   55     1   
2      팬시x팬시         3화   3  43907    9.40       419   521   47     1   
3      팬시x팬시         4화   4  42601    9.40       420   525   47     1   
4      팬시x팬시         5화   5  41786    9.41       366   510   49     1   
...      ...        ...  ..    ...     ...       ...   ...  ...   ...   
2344  포션 매니아      1EP-1   1   3174    9.55      1050     5  256     0   
2345  포션 매니아      1EP-2   2   1731    9.62       920     5  116     0   
2346  포션 매니아  1EP-3 해결편   3    555    9.64       934     3  185     0   
2347  포션 매니아      2EP-1   4    261    9.63       902     2  193     0   
2348  포션 매니아      2EP-2   5    127    9.68       817     1  138     0   

      조회수 대비 별점참여  ...  일상  개그  판타지  액션  드라마  순정  감성  스릴러  시대극  스포츠  
0        8.067775  ...   0   1    0   0    0   1   0    0    0    0  
1        8.730888  ...   0   1    0   0    0   1   0    0    0    0  
2        9.542897  ...   0   1    0   0    0   1   0    0    0    0  
3        9.858923  ...   0   1    0   0    0   1   0    0    0    0  
4        8.758914  ...   0   1    0   0    0   1   0    0    0    0  
...           ...  ...  ..  ..  ...  ..  ...  ..  ..  ...  ...  ...  
2344   330.812854  ...   0   0    1   0    1   0   0    0    0    0  
2345   531.484691  ...   0   0    1   0    1   0   0    0    0    0  
2346  1682.882883  ...   0   0    1   0    1   0   0    0    0    0  
2347  3455.938697  ...   0   0    1   0    1   0   0    0    0    0  
2348  6433.070866  ...   0   0    1   0    1   0   0    0    0    0  

[2349 rows x 26 columns]

In [7]:
# 제목화 회차 제목을 인덱스로 지정
data.index = [data.iloc[:,0],data.iloc[:,1]]

In [8]:
data

웹툰 제목      회차 제목  회차    조회수  회차별 별점  별점 참여인원수  좋아요수  댓글수  \
웹툰 제목  회차 제목                                                                  
팬시x팬시  1화          팬시x팬시         1화   1  69288    9.47       559   693  138   
       2화          팬시x팬시         2화   2  47876    9.48       418   561   55   
       3화          팬시x팬시         3화   3  43907    9.40       419   521   47   
       4화          팬시x팬시         4화   4  42601    9.40       420   525   47   
       5화          팬시x팬시         5화   5  41786    9.41       366   510   49   
...                  ...        ...  ..    ...     ...       ...   ...  ...   
포션 매니아 1EP-1      포션 매니아      1EP-1   1   3174    9.55      1050     5  256   
       1EP-2      포션 매니아      1EP-2   2   1731    9.62       920     5  116   
       1EP-3 해결편  포션 매니아  1EP-3 해결편   3    555    9.64       934     3  185   
       2EP-1      포션 매니아      2EP-1   4    261    9.63       902     2  193   
       2EP-2      포션 매니아      2EP-2   5    127    9.68       817     1  138   

                  정식연재  조회수 대비 별점참여  ...  일상  개그  판타지  액션  드라마  순정  감성  스릴러  \
웹툰 제목  회차 제목                         ...                                      
팬시x팬시  1화            1     8.067775  ...   0   1    0   0    0   1   0    0   
       2화            1     8.730888  ...   0   1    0   0    0   1   0    0   
       3화            1     9.542897  ...   0   1    0   0    0   1   0    0   
       4화            1     9.858923  ...   0   1    0   0    0   1   0    0   
       5화            1     8.758914  ...   0   1    0   0    0   1   0    0   
...                ...          ...  ...  ..  ..  ...  ..  ...  ..  ..  ...   
포션 매니아 1EP-1         0   330.812854  ...   0   0    1   0    1   0   0    0   
       1EP-2         0   531.484691  ...   0   0    1   0    1   0   0    0   
       1EP-3 해결편     0  1682.882883  ...   0   0    1   0    1   0   0    0   
       2EP-1         0  3455.938697  ...   0   0    1   0    1   0   0    0   
       2EP-2         0  6433.070866  ...   0   0    1   0    1   0   0    0   

                  시대극  스포츠  
웹툰 제목  회차 제목                
팬시x팬시  1화           0    0  
       2화           0    0  
       3화           0    0  
       4화           0    0  
       5화           0    0  
...               ...  ...  
포션 매니아 1EP-1        0    0  
       1EP-2        0    0  
       1EP-3 해결편    0    0  
       2EP-1        0    0  
       2EP-2        0    0  

[2349 rows x 26 columns]

In [9]:
# 사용하지 않는 열 삭제
data = data.drop('웹툰 제목', axis = 1)
data = data.drop('회차 제목', axis = 1)
# data = data.drop('등록일', axis = 1)

In [10]:
data

회차    조회수  회차별 별점  별점 참여인원수  좋아요수  댓글수  정식연재  조회수 대비 별점참여  \
웹툰 제목  회차 제목                                                                  
팬시x팬시  1화          1  69288    9.47       559   693  138     1     8.067775   
       2화          2  47876    9.48       418   561   55     1     8.730888   
       3화          3  43907    9.40       419   521   47     1     9.542897   
       4화          4  42601    9.40       420   525   47     1     9.858923   
       5화          5  41786    9.41       366   510   49     1     8.758914   
...               ..    ...     ...       ...   ...  ...   ...          ...   
포션 매니아 1EP-1       1   3174    9.55      1050     5  256     0   330.812854   
       1EP-2       2   1731    9.62       920     5  116     0   531.484691   
       1EP-3 해결편   3    555    9.64       934     3  185     0  1682.882883   
       2EP-1       4    261    9.63       902     2  193     0  3455.938697   
       2EP-2       5    127    9.68       817     1  138     0  6433.070866   

                  조회수 대비 좋아요  댓글수 대비 긍정댓글  ...  일상  개그  판타지  액션  드라마  순정  감성  \
웹툰 제목  회차 제목                               ...                                 
팬시x팬시  1화          10.001732    45.652174  ...   0   1    0   0    0   1   0   
       2화          11.717771    49.090909  ...   0   1    0   0    0   1   0   
       3화          11.865989    29.787234  ...   0   1    0   0    0   1   0   
       4화          12.323654    42.553191  ...   0   1    0   0    0   1   0   
       5화          12.205045    32.653061  ...   0   1    0   0    0   1   0   
...                      ...          ...  ...  ..  ..  ...  ..  ...  ..  ..   
포션 매니아 1EP-1        1.575299    36.718750  ...   0   0    1   0    1   0   0   
       1EP-2        2.888504    31.034483  ...   0   0    1   0    1   0   0   
       1EP-3 해결편    5.405405    37.297297  ...   0   0    1   0    1   0   0   
       2EP-1        7.662835    31.088083  ...   0   0    1   0    1   0   0   
       2EP-2        7.874016    22.463768  ...   0   0    1   0    1   0   0   

                  스릴러  시대극  스포츠  
웹툰 제목  회차 제목                     
팬시x팬시  1화           0    0    0  
       2화           0    0    0  
       3화           0    0    0  
       4화           0    0    0  
       5화           0    0    0  
...               ...  ...  ...  
포션 매니아 1EP-1        0    0    0  
       1EP-2        0    0    0  
       1EP-3 해결편    0    0    0  
       2EP-1        0    0    0  
       2EP-2        0    0    0  

[2349 rows x 24 columns]

In [11]:
# # 조회수, 별점 참여 인원수, 좋아요 수, 댓글 수 삭제
# data2 = data.drop('조회수', axis = 1)
# data2 = data2.drop('별점 참여인원수', axis = 1)
# data2 = data2.drop('좋아요수', axis = 1)
# data2 = data2.drop('댓글수', axis = 1)

In [12]:
# 문제와 정답으로 나누기
data_X = data.drop('정식연재', axis = 1)
data_y = data['정식연재']

In [13]:
# # 문제와 정답으로 나누기
# data_X = data2.drop('정식연재', axis = 1)
# data_y = data2['정식연재']

In [14]:
# train, test 나누기
X_train,X_test,y_train,y_test = train_test_split(data_X,data_y,
                                random_state = 3,
                                test_size = 0.3)

### 디시전트리

In [180]:
tree = DecisionTreeClassifier()

In [181]:
# 교차검증
result = cross_val_score(tree, X_train, y_train, cv=5)
result

array([0.75379939, 0.76899696, 0.75683891, 0.75379939, 0.71646341])

In [182]:
# 학습
tree.fit(X_train, y_train)

DecisionTreeClassifier()

In [183]:
# 평가
tree.score(X_test, y_test)

0.7730496453900709

In [184]:
# 결과 예측 보기
pre = tree.predict(X_test)
pre

array([1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0,
       0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1,

### KNN 

In [185]:
knn = KNeighborsClassifier()

In [186]:
# 학습
knn.fit(X_train,y_train)

KNeighborsClassifier()

In [187]:
# 교차검증
result = cross_val_score(knn, X_train, y_train, cv=5)
result

array([0.64133739, 0.63221884, 0.65349544, 0.55015198, 0.63414634])

In [188]:
# 평가
knn.score(X_test,y_test)

0.6567375886524822

In [189]:
# 성능 좋은 파라미터 찾기(이웃 수 기준)
score_list = []
k = []

for i in range(1,300):
    knn=KNeighborsClassifier(n_neighbors=i)
    knn.fit(X_train,y_train)
    score_list.append(knn.score(X_test,y_test))
    k.append(i)
    
k_score = pd.DataFrame(score_list, k)
k_score = k_score.rename(columns={k_score.columns[0]:"점수"})
k_score.sort_values(by='점수', ascending = False)

점수
34   0.693617
32   0.690780
30   0.690780
26   0.689362
24   0.686525
..        ...
291  0.614184
282  0.614184
280  0.614184
290  0.611348
1    0.601418

[299 rows x 1 columns]

### RandomForest

In [244]:
# forest = RandomForestClassifier(n_estimators=1000, # tree의 개수
#                                       max_features=0.7, # 각각의 트리에서 사용할 특성의 개수
#                                       max_depth=5,
#                                       min_samples_leaf=15,
#                                       max_leaf_nodes=50)
forest = RandomForestClassifier(max_depth=17)

In [245]:
# 학습
forest.fit(X_train,y_train)

RandomForestClassifier(max_depth=17)

In [246]:
# 교차검증
cross_val_score(forest, X_train, y_train, cv=5).mean()

0.861926384461413

In [247]:
cross_val_score(forest, X_test, y_test, cv=5).mean()

0.8170212765957447

In [248]:
forest.score(X_test,y_test)

0.8822695035460993

In [249]:
for i in range(0,21):
    print(cross_val_score(forest, X_train, y_train, cv=5).mean(), end=' ')
    print(cross_val_score(forest, X_test, y_test, cv=5).mean())

0.8643524353176663 0.8212765957446809
0.8661742901623544 0.8099290780141845
0.8607031655422939 0.8198581560283686
0.862530580472978 0.8156028368794326
0.8607031655422936 0.8127659574468085
0.8594892134331678 0.8170212765957446
0.8582697012380459 0.8141843971631205
0.8582715546000446 0.8113475177304965
0.8643505819556676 0.8113475177304965
0.8649658981392244 0.8085106382978724
0.8558269701238045 0.8127659574468085
0.8607050189042923 0.8241134751773049
0.855226480836237 0.8198581560283689
0.8631366298465416 0.8184397163120568
0.8655719475127883 0.822695035460993
0.8546241381866706 0.8212765957446809
0.8631384832085403 0.8127659574468085
0.8661798502483504 0.8113475177304963
0.8564422863073615 0.8198581560283689
0.8588683371636148 0.825531914893617
0.8588850174216027 0.8198581560283689


In [239]:
# 컬럼별 중요도 파악하기
importance = forest.feature_importances_
importance_df = pd.DataFrame(importance,index = X_train.columns).sort_values(by = 0, ascending = False)
importance_df=importance_df.rename(columns={0:'중요도'})
importance_df

중요도
댓글수 대비 긍정댓글  0.168475
별점 참여인원수     0.109331
조회수 대비 좋아요   0.108490
댓글수          0.096630
조회수 대비 별점참여  0.084899
조회수          0.076600
댓글수 대비 부정댓글  0.071292
좋아요수         0.067834
회차별 별점       0.057337
회차           0.022475
판타지          0.021019
스릴러          0.016998
스토리          0.013177
감성           0.012090
일상           0.011659
에피소드         0.011282
드라마          0.011154
순정           0.009817
액션           0.008994
개그           0.008017
옴니버스         0.004794
시대극          0.004625
스포츠          0.003012

### Standard Scaler

In [195]:
scaler = StandardScaler()

In [196]:
# 범위 학습
scaler.fit(X_train)

StandardScaler()

In [197]:
# 학습된 범위로 값 변환
trans_X_train = scaler.transform(X_train)
trans_X_test = scaler.transform(X_test)

In [198]:
# 각 모델별 스케일링 적용한 결과 보기
result_tree = cross_val_score(tree,trans_X_train, y_train, cv=5)
result_knn = cross_val_score(knn,trans_X_train, y_train, cv=5)
result_forest = cross_val_score(forest,trans_X_train, y_train, cv=5)
print("디시전트리 : ",result_tree)
print("평균 : ",result_tree.mean())
print("KNN : ",result_knn)
print("평균 : ",result_knn.mean())
print("랜덤포레스트 : ",result_forest)
print("평균 : ",result_forest.mean())

디시전트리 :  [0.7781155  0.76595745 0.74468085 0.72948328 0.7195122 ]
평균 :  0.7475498554377641
KNN :  [0.71732523 0.72340426 0.70212766 0.67781155 0.73780488]
평균 :  0.7116947142115799
랜덤포레스트 :  [0.87234043 0.8662614  0.87537994 0.83890578 0.86585366]
평균 :  0.8637482393061013


# Robust Scaler

In [199]:
scaler = RobustScaler()

In [200]:
# 범위 학습
scaler.fit(X_train)

RobustScaler()

In [201]:
# 학습된 범위로 값 변환
trans_X_train = scaler.transform(X_train)
trans_X_test = scaler.transform(X_test)

In [202]:
# 각 모델별 스케일링 적용한 결과 보기
result_tree = cross_val_score(tree,trans_X_train, y_train, cv=5)
result_knn = cross_val_score(knn,trans_X_train, y_train, cv=5)
result_forest = cross_val_score(forest,trans_X_train, y_train, cv=5)
print("디시전트리 : ",result_tree)
print("평균 : ",result_tree.mean())
print("KNN : ",result_knn)
print("평균 : ",result_knn.mean())
print("랜덤포레스트 : ",result_forest)
print("평균 : ",result_forest.mean())

디시전트리 :  [0.76595745 0.76595745 0.74772036 0.75987842 0.73780488]
평균 :  0.7554637111720661
KNN :  [0.68693009 0.67781155 0.65653495 0.64133739 0.66158537]
평균 :  0.6648398695233153
랜덤포레스트 :  [0.88145897 0.85714286 0.85410334 0.85410334 0.84756098]
평균 :  0.8588738972496108


# MinMax Scaler

In [203]:
scaler = MinMaxScaler()

In [204]:
# 범위 학습
scaler.fit(X_train)

MinMaxScaler()

In [205]:
# 학습된 범위로 값 변환
trans_X_train = scaler.transform(X_train)
trans_X_test = scaler.transform(X_test)

In [206]:
# 각 모델별 스케일링 적용한 결과 보기
result_tree = cross_val_score(tree,trans_X_train, y_train, cv=5)
result_knn = cross_val_score(knn,trans_X_train, y_train, cv=5)
result_forest = cross_val_score(forest,trans_X_train, y_train, cv=5)
print("디시전트리 : ",result_tree)
print("평균 : ",result_tree.mean())
print("KNN : ",result_knn)
print("평균 : ",result_knn.mean())
print("랜덤포레스트 : ",result_forest)
print("평균 : ",result_forest.mean())

디시전트리 :  [0.76899696 0.75379939 0.75987842 0.7325228  0.72560976]
평균 :  0.7481614648973236
KNN :  [0.64133739 0.67173252 0.66869301 0.64133739 0.68597561]
평균 :  0.6618151827414931
랜덤포레스트 :  [0.88145897 0.8662614  0.87537994 0.84194529 0.84756098]
평균 :  0.8625213136629846


# Normalizer

In [207]:
scaler = MinMaxScaler()

In [208]:
# 범위 학습
scaler.fit(X_train)

MinMaxScaler()

In [209]:
# 학습된 범위로 값 변환
trans_X_train = scaler.transform(X_train)
trans_X_test = scaler.transform(X_test)

In [210]:
# 각 모델별 스케일링 적용한 결과 보기
result_tree = cross_val_score(tree,trans_X_train, y_train, cv=5)
result_knn = cross_val_score(knn,trans_X_train, y_train, cv=5)
result_forest = cross_val_score(forest,trans_X_train, y_train, cv=5)
print("디시전트리 : ",result_tree)
print("평균 : ",result_tree.mean())
print("KNN : ",result_knn)
print("평균 : ",result_knn.mean())
print("랜덤포레스트 : ",result_forest)
print("평균 : ",result_forest.mean())

디시전트리 :  [0.74772036 0.75379939 0.74164134 0.74772036 0.73780488]
평균 :  0.7457372674030692
KNN :  [0.64133739 0.67173252 0.66869301 0.64133739 0.68597561]
평균 :  0.6618151827414931
랜덤포레스트 :  [0.87841945 0.86322188 0.87234043 0.84802432 0.85670732]
평균 :  0.8637426792201053


# Voting

In [211]:
voting = VotingClassifier(
    estimators = [
        ('knn_model',knn),
        ('tree_model',tree),
        ('forest_model',forest)
    ],
    voting = 'soft')

In [212]:
# 학습
voting.fit(X_train,y_train)

VotingClassifier(estimators=[('knn_model',
                              KNeighborsClassifier(n_neighbors=299)),
                             ('tree_model', DecisionTreeClassifier()),
                             ('forest_model',
                              RandomForestClassifier(max_depth=17))],
                 voting='soft')

In [213]:
# 교차검증
result = cross_val_score(voting, X_train, y_train, cv=5)
result

array([0.77203647, 0.77507599, 0.76291793, 0.76595745, 0.72865854])

In [214]:
# 평가
voting.score(X_test,y_test)

0.7673758865248227

# Ada Boosting

In [215]:
adaboost = AdaBoostClassifier()

In [216]:
# 학습
adaboost.fit(X_train,y_train)

AdaBoostClassifier()

In [217]:
# 교차검증
result = cross_val_score(adaboost, X_train, y_train, cv=5)
result

array([0.83282675, 0.7781155 , 0.78723404, 0.76291793, 0.75304878])

In [218]:
# 평가
adaboost.score(X_test,y_test)

0.8014184397163121

# Gradiant Boosting

In [219]:
gbc = GradientBoostingClassifier(max_depth=6)

In [220]:
# 학습
gbc.fit(X_train,y_train)

GradientBoostingClassifier(max_depth=6)

In [221]:
# 교차검증
result = cross_val_score(gbc, X_train, y_train, cv=5)
result.mean()

0.8540032619171175

In [222]:
result = cross_val_score(gbc, X_test, y_test, cv=5)
result.mean()

0.7943262411347518

# 그리드서치

In [223]:
# param_grid={
#     'max_depth' : [5],
#     'n_estimators' :[1500,2000,2500],
#     'max_features' : [0.9,1.0],
#     'max_leaf_nodes' : [200,250,300],
#     'min_samples_leaf' : [3,6,10]
# }

# forest.fit(trans_X_train,y_train)

In [224]:
# grid = GridSearchCV(forest, # GridSearch에 사용할 모델
#                    param_grid, # 튜닝할 매개변수
#                     cv=3 # k겹 교차검증
#                    )

In [225]:
# grid.fit(X_train,y_train)

In [226]:
# #최적의 파라미터
# print('최적의 파라미터 : ',grid.best_params_)
# # 최적의 예측점수
# print('최고 예측 점수 : ',grid.best_score_)

# 랜덤서치

In [227]:
ran = RandomizedSearchCV
from scipy.stats import randint

In [228]:
random_grid={
    'max_depth' : randint(low=1, high=200),
    'max_leaf_nodes' : randint(low=1, high=500),
    'min_samples_leaf' : randint(low=1, high=20),
    'min_samples_split' : randint(low=1, high=10),
    'n_estimators': randint(low=1, high=3000),
    'max_features': randint(low=0.01, high=1.0),
}

In [229]:
ran = RandomizedSearchCV(forest,
                         param_distributions=random_grid,
                         n_iter=1000,
                         cv=2,
                         scoring='accuracy',
                         random_state=42)

In [230]:
# ran.fit(X_train,y_train)

In [231]:
# #최적의 파라미터
# print('최적의 파라미터 : ',ran.best_params_)
# # 최적의 예측점수
# print('최고 예측 점수 : ',ran.best_score_)

# 성능평가지표

In [233]:
print("정확도 : ",accuracy_score(y_test, forest.predict(X_test)))
print("재현율 : ",recall_score(y_test, forest.predict(X_test)))
print("정밀도 : ",precision_score(y_test, forest.predict(X_test)))
print("f1점수 : ",f1_score(y_test, forest.predict(X_test)))

정확도 :  0.873758865248227
재현율 :  0.7732342007434945
정밀도 :  0.8813559322033898
f1점수 :  0.8237623762376237


In [3]:
xgb = XGBClassifier()

In [15]:
xgb.fit(X_train,y_train)

C:\Users\SM2116\anaconda3\lib\site-packages\xgboost\sklearn.py:1146: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[12:02:08] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.4.0/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints='',
              learning_rate=0.300000012, max_delta_step=0, max_depth=6,
              min_child_weight=1, missing=nan, monotone_constraints='()',
              n_estimators=100, n_jobs=16, num_parallel_tree=1, random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, subsample=1,
              tree_method='exact', validate_parameters=1, verbosity=None)

In [18]:
xgb.score(X_test,y_test)

0.8539007092198582